
-- ALTERANDO PROCEDURE
CREATE OR REPLACE PROCEDURE incluir_cliente
(p_ID IN CLIENTE.ID%TYPE, p_RAZAO_SOCIAL IN CLIENTE.RAZAO_SOCIAL%TYPE, p_CNPJ IN CLIENTE.CNPJ%TYPE,
p_SEGMERCADO_ID IN CLIENTE.SEGMERCADO_ID%TYPE, p_FATURAMENTO_PREVISTO IN CLIENTE.FATURAMENTO_PREVISTO%TYPE)
IS
  v_CATEGORIA CLIENTE.CATEGORIA%TYPE;
  v_CNPJ CLIENTE.CNPJ%TYPE := p_CNPJ;
BEGIN
  formata_cnpj(v_CNPJ); -- Procedure para formatar o cnpj
  v_CATEGORIA := categoria_cliente(p_FATURAMENTO_PREVISTO);
  
  INSERT INTO CLIENTE(ID, RAZAO_SOCIAL, CNPJ, SEGMERCADO_ID,DATA_INCLUSAO,FATURAMENTO_PREVISTO,CATEGORIA)
  VALUES(p_ID, p_RAZAO_SOCIAL, v_CNPJ, p_SEGMERCADO_ID, SYSDATE, p_FATURAMENTO_PREVISTO,v_CATEGORIA );
  COMMIT;
END;

-- EXECUTANDO PROCEDURE PASSANDO VALORES
DECLARE

BEGIN
  
  incluir_cliente(1, 'SUPERMERCADO IJK', '67890', 1, 90000);
END;

-- CONSULTANDO O RESULTADO DENTRO DE CLIENTE
SELECT * FROM CLIENTE;



