CREATE OR REPLACE FUNCTION categoria_cliente
(p_FATURAMENTO_PREVISTO IN CLIENTE.FATURAMENTO_PREVISTO%TYPE)
RETURN CLIENTE.CATEGORIA%TYPE
IS
  v_CATEGORIA CLIENTE.CATEGORIA%TYPE;
BEGIN
  IF p_FATURAMENTO_PREVISTO < 10000 THEN
    v_CATEGORIA := 'PEQUENO';
  ELSIF p_FATURAMENTO_PREVISTO < 50000 THEN
    v_CATEGORIA := 'MEDIO';
  ELSIF p_FATURAMENTO_PREVISTO < 100000 THEN
    v_CATEGORIA := 'MEDIO GRANDE';
  ELSE 
     v_CATEGORIA := 'GRANDE';
  END IF;
  RETURN v_CATEGORIA;
END;

-- Executando a função criada a cima e mostrando o resultado!!!!


DECLARE
 v_CATEGORIA CLIENTE.CATEGORIA%TYPE;
BEGIN
  v_CATEGORIA := categoria_cliente(110000);
  dbms_output.put_line(v_categoria);
END;