
DECLARE
  v_ID SEGMERCADO.ID%TYPE := 1;
  v_DESCRICAO SEGMERCADO.DESCRICAO%TYPE;
BEGIN
  SELECT DESCRICAO INTO v_DESCRICAO FROM SEGMERCADO WHERE ID = v_ID;
  dbms_output.put_line(v_DESCRICAO);
  
END;